### ISSUE TITLE
Possible errors: כש- with dependency type "case" instead of "mark"

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_Hebrew#1] opened 2016-04-03 13:59 UTC
The prefix כש- ('when') almost always has the dependency label `mark`, with the following exceptions where it is `case`:

```
$ egrep 'Case=Tem.*case' he-ud-*.conllu
he-ud-dev.conllu:33 כש    _   PART    PART    Case=Tem    35  case    _   _
he-ud-train.conllu:88   כש    _   PART    PART    Case=Tem    90  case    _   _
he-ud-train.conllu:6    כש    _   PART    PART    Case=Tem    7   case    _   _
he-ud-train.conllu:37   כש    _   PART    PART    Case=Tem    39  case    _   _
```

Is this a bug or is there a linguistic difference here? One of the examples is:

ואולם , הבטחה זאת **כשהיא** לעצמה אין בה כל חידוש.

@yoavg

**Comment by yoavg** [comment] 2016-04-05 20:16
These are all variants of כשלעצמה, which are annotated in the original constituency treebank as a PP (the other cases of כש are annotated as an SBAR). So this difference is by design. I tend to agree with the judgement of the original annotators, but am not completely sure. Maybe @rtsarfaty can weigh in?

**Comment by yoavg** [comment] 2016-04-06 11:28
@rtsarfaty also agrees that this should indeed be mark, so I am closing this issue.

**Closed as completed by yoavg** 2016-04-06 11:28 UTC
